# Neos Events Dev bot
DISCORD_BOT_TOKEN = ''
DISCORD_BOT_TOKEN_REFRESH_INTERVAL = 5
# Neos events to aggrerate, in the format of 'scheme://host:port'
SERVERS_EVENT = []
SHOW_WEBUI = true
CLOUDVAR_RESONITE_USER = ""
CLOUDVAR_RESONITE_PASS = ""
CLOUDVAR_BASE_NAME = ""
CLOUDVAR_GENERAL_NAME = ""

PRIVATE_DISCORDS = []
SECRET_KEY = ""
DISCORD_CLIENT_ID = ""
DISCORD_CLIENT_SECRET = ""
DISCORD_REDIRECT_URI = ""
DISCORD_CLIENT_BOT_TOKEN = ""

TWITCH_CLIENT_ID = ""
TWITCH_SECRET = ""
TWITCH_STREAMS = ""
TWITCH_GAME_ID = "1184012414"
TWITCH_RESONITE_ACCOUNT_NAME = "ResoniteApp"