# Neos Events Dev bot
DISCORD_BOT_TOKEN = ''
DISCORD_GUILDS_WHITELISTED = []
# Neos events to aggrerate, in the format of 'scheme://host:port'
SERVERS_EVENT = []
# Google calendars ID to sync
CALENDARS_ACCEPTED = []
# Path to the Google Service Account credentials file
CREDENTIALS_FILE = ''
SHOW_WEBUI = true